name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  http: ^0.13.4
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/bg.jpg
    - assets/icons/

  fonts:
    - family: MarkPro
      fonts:
        - asset: fonts/MarkPro.ttf
    - family: MarkProBold
      fonts:
        - asset: fonts/MarkPro-Bold.ttf
    
 